userver {
    listen 80;
    server_name mosesekerin.name.ng;

    location = / {
        default_type text/html;
        return 200 '<h1>Timileyin-Your-SRE-Guy</h1>';
    }

    location = /api {
        default_type application/json;
        return 200 '{"message":"HNGI14 Stage 1","track":"DevOps","username":"Timileyin-Your-SRE-Guy"}';
    }
}
